### ISSUE TITLE
Needs update for new output syntax changes

### ISSUE THREAD

**Issue by friedmud** [idaholab/stork#24]
Stork needs to be updated for the new output syntax changes.

Currently there is no solver output at all (Is that a bug??)

**Comment by aeslaughter** [comment]
There is probably something wrong, there should be something. I will try to take a look this weekend, but I am already swamped with a movie making project for Rich.

**Comment by friedmud** [comment]
I can fix it... it seems like just turning off legacy output support fixed
it.  Is that ok with you?

**Comment by aeslaughter** [comment]
Thanks, it will be a motivator to stop using legacy support for output. I will get the apps cleaned up next week and be done with it.

**Comment by permcody** [comment]
Fixed by https://github.com/idaholab/stork/commit/3e2e4f63ba5661c4b7627c06d5d566a7d9f671e4 and https://github.com/idaholab/stork/commit/310741cbe01ea80c44960fec9db58e8fe360ab1a
