### ISSUE TITLE
make_new_module.py creates template that uses old constructors

### ISSUE THREAD

**Issue by bwspenc** [idaholab/stork#29]
The <my_module>App.C file created by make_new_module.py got created with old-style constructors. This issue may also apply to other scripts in Stork -- I just ran into this issue when I tried using that particular script.

**Comment by permcody** [comment]
Looks like it's just that script fortunately.

**Comment by bwspenc** [comment]
Also related closely enough to include in this issue is that this script creates a file in the 'unit' directory that contains 'cout', a banned keyword.  Other than these two issues, the script worked great for me.
