### ISSUE TITLE
new module arguments for App constructor

### ISSUE THREAD

**Issue by WilkAndy** [idaholab/stork#30]
the make_new_module script should produce, for example:

PorousFlowApp::PorousFlowApp(const InputParameters &parameters) :
    MooseApp(parameters)

and

public:
  PorousFlowApp(const InputParameters &parameters);

Currently it still has the old moose version that includes the "name" argument.

**Comment by aeslaughter** [comment]
FYI: Only `MooseObjects` use `const InputParameters & parameters`, `Action`
and `MooseApp` objects use a pass-by-value parameters: `InputParameters
parameters`.

**Comment by WilkAndy** [comment]
Oh, thanks @aeslaughter
