### ISSUE TITLE
newly created module unit Makefile slightly incorrect

### ISSUE THREAD

**Issue by WilkAndy** [idaholab/stork#33]
MOOSE_DIR          ?= $(shell dirname `pwd`)/../moose

should possibly be (?)

MOOSE_DIR          ?= $(shell dirname `pwd`)/../../../moose

**Comment by permcody** [comment]
That might be true for modules but it's correct for new applications which
is the normal case. Based on my other response (not creating separate unit
tests for each module). I don't think I'm too worried about fixing this up.

**Comment by WilkAndy** [comment]
Aha, ok, let's close this one.

a
